services:
  - type: web
    name: deal-mvp
    env: docker
    plan: starter
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: "5000"
      - key: DATABASE_URL
        value: "postgres://{user}:{password}@{host}:{port}/{dbname}"
  - type: postgres
    name: deal-mvp-db
    plan: starter
    region: oregon
    databaseName: deals
